# Generated by Django 3.0.7 on 2020-06-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
