# Generated by Django 3.0.7 on 2020-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='type',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='item',
            field=models.CharField(blank=True, default=None, max_length=69),
        ),
    ]
