# Generated by Django 3.0.7 on 2020-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200608_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.CharField(blank=True, default=None, max_length=69),
        ),
    ]
