# Generated by Django 3.0.7 on 2020-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200608_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='item',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='name',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='size',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='topping1',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='topping2',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='topping3',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
