# Generated by Django 3.0.7 on 2020-06-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200608_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
