# Generated by Django 3.0.7 on 2020-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200608_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='extras',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], max_length=10, null=True),
        ),
    ]
