# Generated by Django 3.0.7 on 2020-06-08 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200608_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
