# Generated by Django 3.0.7 on 2020-06-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='extra_count',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
