# Generated by Django 3.0.7 on 2020-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_sub_extra_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='extras',
            new_name='extra1',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='extra2',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='extra3',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
